set SERVEROUTPUT on;

create or replace PACKAGE ACTIVIDAD_TIPOS_BLOQUES as
    FUNCTION CONTAR_MODIFICACIONES RETURN NUMBER;
    PROCEDURE MODIFICAR_TORRE;
end ACTIVIDAD_TIPOS_BLOQUES;

CREATE OR REPLACE PACKAGE BODY ACTIVIDAD_TIPOS_BLOQUES AS

    PROCEDURE MODIFICAR_TORRE(P_ID IN UNIDAD_INTERNA.ID_UNIDAD%TYPE, P_NUEVATORRE IN UNIDAD_INTERNA.NUM_TORRE%TYPE, 
    PH_ID IN H_UNIDAD_INTERNA.ID_UNIDAD%TYPE, PH_NUEVATORRE IN H_UNIDAD_INTERNA.NUM_TORRE%TYPE  ) IS 
    BEGIN
        UPDATE unidad_interna SET num_torre = p_nuevatorre WHERE id_unidad = P_ID;
        UPDATE H_unidad_interna SET num_torre = pH_nuevatorre WHERE id_unidad = PH_ID;
        COMMIT;
    END;
    
    TRIGGER
    
    
    
    
    
    
    
END ACTIVIDAD_TIPOS_BLOQUES;

ALTER TABLE H_UNIDAD_INTERNA RENAME COLUMN COLUMN1 TO NOMBRE_UNIDAD;